title: The Nightwatchman

'One Man Revolution':
    "California's Dark":
        id: xVAVc7MIWP8
    'One Man Revolution':
        id: yU23yBrT-_A
    'Let Freedom Ring':
        id: 8fNhpgLp2Po
    'The Road I Must Travel':
        id: KFbmAHWGE3w
    'The Garden of Gethsemane':
        id: A8EY4ZWiokM
    'House Gone Up in Flames':
        id: gdWb-j_w2Iw
    'Flesh Shapes the Day':
        id: o_wjKDR7r6Y
    'Battle Hymns':
        id: Y_3dhLpuuOc
    'Maximum Firepower':
        id: VBy0xWIG8do
    'Union Song':
        id: qT5diwh4gq8
    'No One Left':
        id: jynhXVN-D14
    'The Dark Clouds Above':
        id: YU3a1AuzI2c
    'Until the End':
        id: ZbOFM68aC8o

'The Fabled City':
    'The Fabled City':
        id: eTxjbgUt6H8
    'Whatever It Takes':
        id: pPjvtorTt8U
    'The King of Hell':
        id: R0aWOX1zu9A
    'Night Falls':
        id: I8X-6QSZeAg
    'The Lights Are On in Spidertown':
        id: tehAPIxD8Nc
    'Midnight in the City of Destruction':
        id: QNHPx718V3k
    'Saint Isabelle':
        id: j4HfGBLY-FE
    'Lazarus On Down':
        id: -PohES7Vmho
    'Gone Like Rain':
        id: HW0fWdKTt_k
    'The Iron Wheel':
        id: yJK8nDYL6aI
    'Rise to Power':
        id: TmQ7NlO6Tv4

'Union Town':
    'Union Town':
        id: uinygtFlOCA
    'Solidarity Forever':
        id: czQh1vj1jF8
    'Which Side Are You On?':
        id: YFUMEKD620w
    'A Wall Against the Wind':
        id: 1P3PnbRFd_c
    '16 Tons':
        id: knwaFenE7FQ
    'This Land Is Your Land':
        id: lZ-UgAUEPa0
    'I Dreamed I Saw Joe Hill Last Night':
        id: FwFG9X1fmf0

'World Wide Rebel Songs':
    'Black Spartacus Heart Attack Machine':
        id: 9ftQOWPWZZU
    'The Dogs of Tijuana':
        id: BmktWE4o1sk
    'It Begins Tonight':
        id: kr6ElWQg7Zo
    'Save the Hammer for the Man':
        id: lpmRU2TPJ-Y
    'The Fifth Horseman of the Apocalypse':
        id: 73tz8bZPvG0
    'Speak and Make Lightning':
        id: -UtueH3QOt8
    'Facing Mount Kenya':
        id: s0pjU5Ek8Z8
    'The Whirlwind':
        id: Pr8nPhIJFxY
    'Stray Bullets':
        id: Xrq-JzSAug8
    'Branding Iron':
        id: UPQ9OxStzRg
    'World Wide Rebel Songs':
        id: 60ZfJCWglbU
    'God Help Us All':
        id: 8H5VMJG5qmg
