on:
  push:
    branches: [ 'main' ]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update_readme:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.update_readme.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v4
      - uses: kubawerlos/youtube-songs@v1
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        id: update_readme
        with:
          commit_message: Update README.md
  publish:
    runs-on: ubuntu-latest
    needs: update_readme
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.update_readme.outputs.commit_hash }}
      - run: echo '{"markdown-to-html":{"document":{"title":"The Nightwatchman"}}}' > .markdown-to-html-cli.config.json
      - uses: jaywcjlove/markdown-to-html-cli@main
        with:
          config: .markdown-to-html-cli.config.json
          dark-mode: false
          favicon: https://avatars.githubusercontent.com/u/151223147
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - uses: actions/deploy-pages@v4
